from setuptools import setup, find_packages

setup(
    name='recapi',
    version='0.0.1',
    description='implicit feedback recommender API',
    author='Christoph Schock',
    author_email='chschock@gmail.com',
    license='MIT',

    packages=find_packages(),
    install_requires=[
        'aniso8601==1.2.0',
        'click==6.7',
        'Flask==0.12',
        'Flask-RESTful==0.3.5',
        'Flask-SQLAlchemy==2.1',
        'itsdangerous==0.24',
        'Jinja2==2.9.5',
        'MarkupSafe==0.23',
        'nose==1.3.7',
        'numpy',
        'psycopg2==2.6.2',
        'python-dateutil==2.6.0',
        'pytz==2016.10',
        'recapi==0.0.1',
        'requests==2.13.0',
        'scikit-learn==0.18.1',
        'scipy==0.18.1',
        'six==1.10.0',
        'sklearn==0.0',
        'SQLAlchemy==1.1.5',
        'Werkzeug==0.11.15',
    ],
)
